### ISSUE TITLE
Boot.elf on root

### ISSUE THREAD

**Issue by chronoss09** [GaryOderNichts/bluebomb_micro#1]
It's not a issue but just to know, wich port to connect the usb drive ?
And, it's not compatible with the SD Card and a boot.elf on root ?

Thanks for your great work, with that, it's easy to hack the wii and maybe the wii mini 🥇

**Comment by GaryOderNichts** [comment]
The stage1 which comes with BlueBomb Micro is the same as the one from the original BlueBomb.
See the following guide for more detailed instructions on how to set up the USB drive: <https://wii.hacks.guide/bluebomb.html#instructions>
