### ISSUE TITLE
Customize stage0.bin

### ISSUE THREAD

**Issue by david-zzj** [GaryOderNichts/bluebomb_micro#2]
This is a very good and creative project.
Can i use my customize stage0.bin to build the uf2 file？
And how to？

**Comment by GaryOderNichts** [comment]
The BlueBomb stage0 and stage1 are included as byte arrays [here](https://github.com/GaryOderNichts/bluebomb_micro/blob/main/components/bluebomb_micro/stage0_bin.h) and [here](https://github.com/GaryOderNichts/bluebomb_micro/blob/main/components/bluebomb_micro/stage1_bin.h).
If you mean the `WII_SMX_XX.bin` or `MINI_SM_XXX.bin` files, they have been placed into a list for cmake [here](https://github.com/GaryOderNichts/bluebomb_micro/blob/main/cmake/l2cb_list.cmake).

**Comment by david-zzj** [comment]
I saw the cmake pages. But there is some confusion. For example:

set(WII_SM4_3U 0x811725e0)
list(APPEND BLUEBOMB_L2CB_LIST WII_SM4_3U)
After compile, it will generate the “bluebomb_WII_SM4_3U.uf2” file.

If i want to make a game (eg. WII_XX_YY 0x803c15c0), and generate “bluebomb_WII_XX_YY.uf2” file.
How can i do that?

**Comment by GaryOderNichts** [comment]
You can add that game to the `l2cb_list.cmake` file by adding the following to it:
```cmake
set(WII_XX_YY 0x803c15c0)
list(APPEND BLUEBOMB_L2CB_LIST WII_XX_YY)
```
Then when building, configure the project with `cmake .. -DBLUEBOMB_TARGET="WII_XX_YY"`.

**Comment by david-zzj** [comment]
I have Set up the [pico-sdk], and Run cmake .. -DBLUEBOMB_TARGET="WII_SM4_3J" (replace WII_XX_YY).
It looked like something missing, please have a look.

![2024-04-26 003644](https://github.com/GaryOderNichts/bluebomb_micro/assets/22125266/d1ca349c-3a69-461a-8ad8-6d9876937ecf)

**Comment by GaryOderNichts** [comment]
You need to intialize the git submodules in this repo by running `git submodule update --init` or cloning the repo with `--recursive`.

**Comment by david-zzj** [comment]
Thanks @GaryOderNichts ，i finally got my WII_XX_YY.uf2 file.
